on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v3
      - name: 📦 Create zip file for notifier
        run: |
          cd "${{ github.workspace }}/apps"
          zip -r notifier.zip notifier
      - name: 📤 Upload the zip file as a release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "${{ github.workspace }}/apps/notifier.zip"
          asset_name: notifier.zip
          tag: ${{ github.ref }}
          overwrite: true
